AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  TelemetryDataTableName:
    Description: Name of the DynamoDB table
    Value:
      Ref: TelemetryData
  TelemetryProcessorFunctionArn:
    Description: ARN of the Lambda function
    Value:
      Fn::GetAtt:
      - TelemetryProcessor
      - Arn
  TelemetryProcessorQueueURL:
    Description: URL of the SQS queue
    Value:
      Ref: TelemetryProcessorQueue
Parameters:
  ImageUri:
    Description: URI of the ECR image for the Lambda function
    Type: String
Resources:
  TelemetryData:
    Properties:
      AttributeDefinitions:
      - AttributeName: vehicleId
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: S
      KeySchema:
      - AttributeName: vehicleId
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: TelemetryData
    Type: AWS::DynamoDB::Table
  TelemetryProcessor:
    Properties:
      Code:
        ImageUri:
          Ref: ImageUri
      Environment:
        Variables:
          QUEUE_URL:
            Ref: TelemetryProcessorQueue
          TABLE_NAME:
            Ref: TelemetryData
      FunctionName: TelemetryProcessor
      MemorySize: 128
      PackageType: Image
      Role:
        Fn::GetAtt:
        - TelemetryProcessorRole
        - Arn
      Timeout: 30
    Type: AWS::Lambda::Function
  TelemetryProcessorEventSourceMapping:
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn:
        Fn::GetAtt:
        - TelemetryProcessorQueue
        - Arn
      FunctionName:
        Fn::GetAtt:
        - TelemetryProcessor
        - Arn
      FunctionResponseTypes:
      - ReportBatchItemFailures
    Type: AWS::Lambda::EventSourceMapping
  TelemetryProcessorQueue:
    Properties:
      QueueName: TelemetryProcessorQueue
    Type: AWS::SQS::Queue
  TelemetryProcessorQueuePolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action: sqs:SendMessage
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::GetAtt:
            - TelemetryProcessorQueue
            - Arn
        Version: '2012-10-17'
      Queues:
      - Ref: TelemetryProcessorQueue
    Type: AWS::SQS::QueuePolicy
  TelemetryProcessorRole:
    Properties:
      RoleName: TelemetryProcessorRole-123 
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          - Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::GetAtt:
              - TelemetryProcessorQueue
              - Arn
          - Action:
            - dynamodb:PutItem
            Effect: Allow
            Resource:
              Fn::GetAtt:
              - TelemetryData
              - Arn
          - Action:
            - sns:ListTopics
            Effect: Allow
            Resource: "*"
          Version: '2012-10-17'
        PolicyName: TelemetryProcessorPolicy
    Type: AWS::IAM::Role
