
AWSTemplateFormatVersion: '2010-09-09'
Description: IoT Core setup to forward telemetry to an existing SQS queue and create a Thing and Policy

Parameters:
  TelemetryQueueUrl:
    Type: String
    Description: The URL of the existing TelemetryProcessorQueue
  TelemetryQueueArn:
    Type: String
    Description: The ARN of the existing TelemetryProcessorQueue

Resources:
  IoTToSQSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IoTToSQSRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: IoTToSQSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !Ref TelemetryQueueArn

  TelemetryRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: TelemetryToSQS
      TopicRulePayload:
        sql: "SELECT * FROM 'vehicle/telemetry/#'"
        actions:
          - sqs:
              roleArn: !GetAtt IoTToSQSRole.Arn
              queueUrl: !Ref TelemetryQueueUrl
        ruleDisabled: false

  VehicleThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: VehicleDevice

  VehiclePolicy2:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iot:Connect
              - iot:Publish
              - iot:Subscribe
              - iot:Receive
            Resource: "*"

Outputs:
  GeneratedPolicyName:
    Description: The name of the generated IoT policy
    Value: !Ref VehiclePolicy2