name: CI/CD for TelemetryProcessor
'on':
  push:
    paths:
      - 'TelemetryProcessor/**'
  pull_request:
    paths:
      - 'TelemetryProcessor/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore TelemetryProcessor/TelemetryProcessor.sln
      
    - name: Build
      run: >-
        dotnet build TelemetryProcessor/TelemetryProcessor.sln --configuration Release
        --no-restore
        
    - name: Run tests
      run: dotnet test TelemetryProcessor/TelemetryProcessor.sln --configuration Release --no-build --verbosity normal
      
  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_SECRET_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get latest tag
        uses: actions/github-script@main
        id: get-tag
        with:
          script: |
            echo "Getting in"
            const { data } = await github.request("GET /repos/{owner}/{repo}/pulls/{pr}", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pr: context.payload.pull_request.number
            });
            if (data.milestone) {
              echo "has milestone"
              core.info(`This pull request has a milestone set: ${data.milestone.title}`);
              NEW_TAG="TelemetryProcessor-${data.milestone.title}"
            } else {
              echo "will fail"
              core.setFailed(`A maintainer needs to set the milestone for this pull request.`);
            }
    
      - name: Create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.get-tag.outputs.new_tag }}
          git push origin ${{ steps.get-tag.outputs.new_tag }}
    
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-tag.outputs.new_tag }}
          name: Release ${{ steps.get-tag.outputs.new_tag }}
          body: |
           🚀 Release for TelemetryProcessor
           - Docker image: `${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.get-tag.outputs.new_tag }}`

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: navora
          IMAGE_TAG: ${{ steps.get-tag.outputs.new_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG TelemetryProcessor/TelemetryProcessor
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG